// Generated by CoffeeScript 1.7.1

/*
  NOTE: this is just a nodejs script for receiving messages from PubNub
 */

(function() {
  var channel, pubnub;

  channel = process.argv[2];

  pubnub = require("pubnub").init({
    publish_key: "pub-c-03930876-06f1-43cc-b979-edb641836a26",
    subscribe_key: "sub-c-aa6ca7c2-60fe-11e6-93e5-0619f8945a4f",
    uuid: "your_name_here" + Math.floor(Math.random() * 1000)
  });

  pubnub.subscribe({
    channel: channel,
    message: function() {
      return console.log(JSON.stringify(arguments));
    }
  });

}).call(this);
